#include "A.h"




void A::perimeter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-41df9546:16deece62a7:-8000:0000000000000C02 begin
{
}
// section 127-0-0-1-41df9546:16deece62a7:-8000:0000000000000C02 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::size()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-41df9546:16deece62a7:-8000:0000000000000C19 begin
{
}
// section 127-0-0-1-41df9546:16deece62a7:-8000:0000000000000C19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
